"""Generate solo-learn pretrain configs for the embedding-quality sweep.

Produces 5 configs per method (vicreg / vicreg_exp / vicreg_ctr) on CIFAR-100 with a
ResNet-18 backbone. The 5 variants deliberately move the *geometry* of the embeddings
(the covariance / variance terms + embedding dimension), so the models span a range of
embedding ranks and downstream accuracies — which is exactly what a RankMe-style
"does a geometric metric predict linear accuracy?" study needs.

Base config is solo-learn's scripts/pretrain/cifar/vicreg.yaml, adapted to CIFAR-100.

Run:  python generate_configs.py
"""
import os

# --- knobs ------------------------------------------------------------------
# Supervisor: 50 epochs is enough. Gives a clean quality spread fast (~15-20 min/model
# on a Kaggle GPU). Bump higher only if the team later wants the literature number.
EPOCHS = 50
TAU = 0.5  # temperature for the exp/ctr LogSumExp criterion — VERIFY vs paper App. L

ROOT = os.path.dirname(os.path.abspath(__file__))

# --- the 5-model hyperparameter sweep (applied to every method) -------------
# HYPERPARAMETER = pretraining learning rate (universal across all SSL methods, so the
# whole group varies the SAME knob -> cross-method comparison is apples-to-apples; this
# is also the axis RankMe sweeps). Everything else is fixed at solo-learn's tuned values.
# grid: {0.1, 0.2, 0.3, 0.5, 1.0}, base = 0.3
# (suffix, lr, note)
VARIANTS = [
    ("lr0p1", 0.1, "low LR"),
    ("lr0p2", 0.2, "below default"),
    ("lr0p3", 0.3, "default / reference (solo-learn tuned)"),
    ("lr0p5", 0.5, "above default"),
    ("lr1p0", 1.0, "high LR (expected degraded)"),
]

METHODS = [
    ("vicreg",     "vicreg",     False),
    ("vicreg_exp", "vicreg_exp", True),
    ("vicreg_ctr", "vicreg_ctr", True),
]

TEMPLATE = """\
# {note}
# Auto-generated by generate_configs.py — edit there, not here.
defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

name: "{name}"
method: "{method}"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  sim_loss_weight: 25.0
  var_loss_weight: 25.0
  cov_loss_weight: 1.0{tau_line}
data:
  dataset: cifar100
  train_path: "./datasets"
  val_path: "./datasets"
  format: "image_folder"
  num_workers: 4
augmentations:
  - rrc:
      enabled: True
      crop_min_scale: 0.2
      crop_max_scale: 1.0
    color_jitter:
      enabled: True
      brightness: 0.4
      contrast: 0.4
      saturation: 0.2
      hue: 0.1
      prob: 0.8
    grayscale:
      enabled: True
      prob: 0.2
    gaussian_blur:
      enabled: False
      prob: 0.0
    solarization:
      enabled: True
      prob: 0.1
    equalization:
      enabled: False
      prob: 0.0
    horizontal_flip:
      enabled: True
      prob: 0.5
    crop_size: 32
    num_crops: 2
optimizer:
  name: "lars"
  batch_size: 256
  lr: {lr}
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

max_epochs: {epochs}
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
"""


def main():
    n = 0
    for folder, method_name, needs_tau in METHODS:
        out_dir = os.path.join(ROOT, folder, "configs")
        os.makedirs(out_dir, exist_ok=True)
        for suffix, lr, note in VARIANTS:
            tau_line = f"\n  tau: {TAU}" if needs_tau else ""
            cfg = TEMPLATE.format(
                note=f"{method_name} / cifar100 / {suffix} (lr={lr}): {note}",
                name=f"{method_name}-cifar100-{suffix}",
                method=method_name,
                lr=lr,
                tau_line=tau_line, epochs=EPOCHS,
            )
            path = os.path.join(out_dir, f"cifar100_{suffix}.yaml")
            with open(path, "w") as f:
                f.write(cfg)
            n += 1
            print(f"wrote {os.path.relpath(path, ROOT)}")
    print(f"\n{n} configs generated ({len(METHODS)} methods x {len(VARIANTS)} variants).")


if __name__ == "__main__":
    main()
