"""Generate solo-learn pretrain configs for the embedding-quality sweep.

Produces 5 configs per method (vicreg / vicreg_exp / vicreg_ctr) on CIFAR-100 with a
ResNet-18 backbone. The 5 variants deliberately move the *geometry* of the embeddings
(the covariance / variance terms + embedding dimension), so the models span a range of
embedding ranks and downstream accuracies — which is exactly what a RankMe-style
"does a geometric metric predict linear accuracy?" study needs.

Base config is solo-learn's scripts/pretrain/cifar/vicreg.yaml, adapted to CIFAR-100.

Run:  python generate_configs.py
"""
import os

# --- knobs ------------------------------------------------------------------
LR = 0.3   # fixed at solo-learn's tuned value
TAU = 0.5  # temperature for the exp/ctr LogSumExp criterion — VERIFY vs paper App. L

ROOT = os.path.dirname(os.path.abspath(__file__))

# --- the 5-model sweep (applied to every method) ----------------------------
# VARIED AXIS = training DURATION (number of epochs), at fixed lr=0.3. This is the
# paper's VICReg experiment (IdEst Fig 5a): as epochs increase, linear accuracy rises
# and IdEst falls -> a REAL spread of representation qualities and a clean negative
# IdEst<->accuracy correlation. (Varying lr alone barely moves quality under LARS, so it
# produced no spread — hence this axis instead.)
# grid: {2, 5, 10, 20, 40} epochs
# (suffix, epochs, note)
VARIANTS = [
    ("ep2",   2,  "very undertrained (worst)"),
    ("ep5",   5,  "undertrained"),
    ("ep10", 10,  "mid"),
    ("ep20", 20,  "good"),
    ("ep40", 40,  "most trained (best)"),
]

METHODS = [
    ("vicreg",     "vicreg",     False),
    ("vicreg_exp", "vicreg_exp", True),
    ("vicreg_ctr", "vicreg_ctr", True),
]

TEMPLATE = """\
# {note}
# Auto-generated by generate_configs.py — edit there, not here.
defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

name: "{name}"
method: "{method}"
wandb:
  enabled: False
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  sim_loss_weight: 25.0
  var_loss_weight: 25.0
  cov_loss_weight: 1.0{tau_line}
data:
  dataset: cifar100
  train_path: "./datasets"
  val_path: "./datasets"
  format: "image_folder"
  num_workers: 4
augmentations:
  - rrc:
      enabled: True
      crop_min_scale: 0.2
      crop_max_scale: 1.0
    color_jitter:
      enabled: True
      brightness: 0.4
      contrast: 0.4
      saturation: 0.2
      hue: 0.1
      prob: 0.8
    grayscale:
      enabled: True
      prob: 0.2
    gaussian_blur:
      enabled: False
      prob: 0.0
    solarization:
      enabled: True
      prob: 0.1
    equalization:
      enabled: False
      prob: 0.0
    horizontal_flip:
      enabled: True
      prob: 0.5
    crop_size: 32
    num_crops: 2
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

max_epochs: {epochs}
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
"""


def main():
    n = 0
    for folder, method_name, needs_tau in METHODS:
        out_dir = os.path.join(ROOT, folder, "configs")
        os.makedirs(out_dir, exist_ok=True)
        for suffix, epochs, note in VARIANTS:
            tau_line = f"\n  tau: {TAU}" if needs_tau else ""
            cfg = TEMPLATE.format(
                note=f"{method_name} / cifar100 / {suffix} ({epochs} epochs): {note}",
                name=f"{method_name}-cifar100-{suffix}",
                method=method_name,
                tau_line=tau_line, epochs=epochs,
            )
            path = os.path.join(out_dir, f"cifar100_{suffix}.yaml")
            with open(path, "w") as f:
                f.write(cfg)
            n += 1
            print(f"wrote {os.path.relpath(path, ROOT)}")
    print(f"\n{n} configs generated ({len(METHODS)} methods x {len(VARIANTS)} variants).")


if __name__ == "__main__":
    main()
